INSERT OR IGNORE INTO User
(
	id,
	name, 
	screenName, 
	location, 
	description, 
	profileImageUrl, 
	url, 
	firstName, 
	lastName, 
	twitterId, 
	isProtected, 
	friendCount, 
	followersCount, 
	createdAt, 
	favouritesCount, 
	utcOffset, 
	timeZone, 
	notifications, 
	statusesCount, 
	profileBackgroundColor, 
	profileTextColor, 
	profileLinkColor, 
	profileSidebarFillColor, 
	profileSidebarBorderColor, 
	profileBackgroundImageUrl, 
	profileBackgroundTile, 
	statusId, 
	profileUserBackgroundImage, 
	defaultProfileImage, 
	isTranslator, 
	followRequestSent, 
	contributorsEnabled, 
	defaultProfile, 
	listedCount, 
	language, 
	geoEnabled, 
	verified, 
	showAllInlineMedia, 
	following, 
	follower, 
	blocked
)
VALUES
(
	:id,
	:name, 
	:screenName, 
	:location, 
	:description, 
	:profileImageUrl, 
	:url, 
	:firstName, 
	:lastName, 
	:twitterId, 
	:isProtected, 
	:friendCount, 
	:followersCount, 
	:createdAt, 
	:favouritesCount, 
	:utcOffset, 
	:timeZone, 
	:notifications, 
	:statusesCount, 
	:profileBackgroundColor, 
	:profileTextColor, 
	:profileLinkColor, 
	:profileSidebarFillColor, 
	:profileSidebarBorderColor, 
	:profileBackgroundImageUrl, 
	:profileBackgroundTile, 
	:statusId, 
	:profileUserBackgroundImage, 
	:defaultProfileImage, 
	:isTranslator, 
	:followRequestSent, 
	:contributorsEnabled, 
	:defaultProfile, 
	:listedCount, 
	:language, 
	:geoEnabled, 
	:verified, 
	:showAllInlineMedia, 
	:following, 
	:follower, 
	:blocked
);


UPDATE OR IGNORE User
SET
	name = :name, 
	screenName = :screenName, 
	location = :location, 
	description = :description, 
	profileImageUrl = :profileImageUrl, 
	url = :url, 
	firstName = :firstName, 
	lastName = :lastName, 
	twitterId = :twitterId, 
	isProtected = :isProtected, 
	friendCount = :friendCount, 
	followersCount = :followersCount, 
	createdAt = :createdAt, 
	favouritesCount = :favouritesCount, 
	utcOffset = :utcOffset, 
	timeZone = :timeZone, 
	notifications = :notifications, 
	statusesCount = :statusesCount, 
	profileBackgroundColor = :profileBackgroundColor, 
	profileTextColor = :profileTextColor, 
	profileLinkColor = :profileLinkColor, 
	profileSidebarFillColor = :profileSidebarFillColor, 
	profileSidebarBorderColor = :profileSidebarBorderColor, 
	profileBackgroundImageUrl = :profileBackgroundImageUrl, 
	profileBackgroundTile = :profileBackgroundTile, 
	statusId = :statusId, 
	profileUserBackgroundImage = :profileUserBackgroundImage, 
	defaultProfileImage = :defaultProfileImage, 
	isTranslator = :isTranslator, 
	followRequestSent = :followRequestSent, 
	contributorsEnabled = :contributorsEnabled, 
	defaultProfile = :defaultProfile, 
	listedCount = :listedCount, 
	language = :language, 
	geoEnabled = :geoEnabled, 
	verified = :verified, 
	showAllInlineMedia = :showAllInlineMedia, 
	following = :following, 
	follower = :follower, 
	blocked = :blocked
WHERE id = :id 
OR twitterId = :twitterId;
