CREATE TABLE "Status" (
	"id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"twitterId" VARCHAR UNIQUE,  
	"createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"text" TEXT, 
	"source" VARCHAR, 
	"geo" VARCHAR, 
	"coordinates" VARCHAR, 
	"truncated" BOOL, 
	"inReplyToStatusId" VARCHAR, 
	"inReplyToUserId" VARCHAR,
	"inReplyToScreenName" VARCHAR,
	"contributors" VARCHAR, 
	"retweeted" BOOL, 
	"retweetCount" INTEGER,
	"retweetedStatusTwitterId" VARCHAR,
	"retweetedStatusId" INT, 
	"possiblySensitive" BOOL, 
	"searchType" VARCHAR, 
	"isMention" BOOL, 
	"statusType" VARCHAR, 
	"placeId" INTEGER, 
	"twitterPlaceId" VARCHAR,
	"userId" INTEGER,
	"twitterUserId" VARCHAR,
	"favorited" BOOL,
	"annotations" TEXT
);