CREATE TABLE "Status" (
	"id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , 
	"createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"text" TEXT, 
	"source" VARCHAR, 
	"twitterUser" VARCHAR, 
	"geo" VARCHAR, 
	"latitude" FLOAT, 
	"longitude" FLOAT, 
	"coordinates" VARCHAR, 
	"twitterId" VARCHAR UNIQUE, 
	"truncated" BOOL, 
	"inReplyToStatusId" VARCHAR, 
	"inReplyToUserId" VARCHAR, 
	"contributors" VARCHAR, 
	"retweetCount" INTEGER, 
	"possiblySensitive" BOOL, 
	"searchType" VARCHAR, 
	"isMention" BOOL, 
	"retweetedStatus" VARCHAR, 
	"statusType" VARCHAR, 
	"placeId" INTEGER, 
	"userId" INTEGER
);