UPDATE Status
SET
	createdAt = :createdAt,
	text = :text,
	source = :source,
	twitterUserId = :twitterUserId,
	geo = :geo,
	placeId = :placeId,
	twitterPlaceId = :twitterPlaceId,
	coordinates = :coordinates,
	twitterId = :twitterId,
	truncated = :truncated,
	inReplyToStatusId = :inReplyToStatusId,
	inReplyToUserId = :inReplyToUserId,
	inReplyToScreeName = :inReplyToScreenName,
	contributors = :contributors,
	retweeted = :retweeted,
	retweetCount = :retweetCount,
	retweetedStatusTwitterId = :retweetedStatusTwitterId,
	retweetedStatusId = :retweetedStatusId,
	possiblySensitive = :possiblySensitive,
	searchType = :searchType,
	isMention = :isMention,
	statusType = :statusType,
	userId = :userId,
	favorited = :favorited,
	annotations = :annotations
WHERE id = :id;